# Generated by Django 4.2.8 on 2023-12-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
        ('rides', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='passengers',
            field=models.ManyToManyField(related_name='passengers_ride', to='users.passenger'),
        ),
    ]
