# Generated by Django 4.2.4 on 2023-12-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_role'),
        ('rides', '0005_alter_ride_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='passengers',
            field=models.ManyToManyField(blank=True, default=[], related_name='passengers_ride', to='users.passenger'),
        ),
    ]
