# Generated by Django 4.2.8 on 2023-12-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_alter_ride_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
