# Generated by Django 4.2.8 on 2023-12-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_passengers'),
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='rides',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengers_ride', to='rides.ride'),
        ),
    ]
