# Generated by Django 4.2.4 on 2023-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_passenger_rides'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='role',
            field=models.CharField(default='driver', editable=False, max_length=255),
        ),
    ]
