# Generated by Django 4.2.4 on 2023-12-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_driver_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='role',
            field=models.CharField(default='passenger', editable=False, max_length=255),
        ),
    ]
