# Generated by Django 4.2.4 on 2023-12-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passenger_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='role',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', editable=False, max_length=255),
        ),
    ]
