# Generated by Django 4.2.4 on 2023-12-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_driver_role_remove_passenger_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='driver', max_length=255),
        ),
    ]
