# Generated by Django 4.2.8 on 2023-12-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='seats',
            field=models.IntegerField(default=5),
        ),
    ]
